apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::486122642263:role
spec:
  containers:
  - image: fstab/aws-cli
    command:
      - "/home/aws/aws/env/bin/aws"
      - "s3"
      - "ls"
      - "xz-webapp"
    name: aws-cli